#sqlite:
#  dbName: ./data/sqlite/data.db  #本地sqlite的名字
app:
  publicKey: A8WLqHTjcT/FQ2IWhIePNShUEcdCzu5dG+XrQU8OMu54
  privateKey: yScdp6fNgUU+cRUTygvJG4EBhDKmOMRrK4XJ9mKVQJ8=
spring:
  datasource:
    url: jdbc:sqlite:./data/sqlite/data.db
    driver-class-name: org.sqlite.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
